use active username rather than username stored in mongo
kurzgesagt-in-a-nutshell/birdbot pull request #225
Opened 2024-07-10 01:27 UTC by arcinfini

Resolves #205 

A simple one-liner solution.

2024-07-10 04:46 UTC, sloth-ontabasco requested changes
I notice that you are assigning the latest display_name in the constructor. Are we ever calling this constructor in the context of a user that does not exist in the server? If so, would those cases be handled without exception?

2024-07-10 11:58 UTC, arcinfini commented
@sloth-ontabasco with the new discord username system the display name is their global nickname they have assigned to themselves. In my case it would be Source instead of arcinfini which is my unique discord username.

2024-07-10 12:08 UTC, arcinfini commented
<img width="310" alt="image" src="https://github.com/kurzgesagt-in-a-nutshell/birdbot/assets/55605311/d007c9f5-e854-4679-9161-76414aedd16a">

Tested with a bot that is not in a server with you. It gets the display_name property correctly.

2024-07-11 06:25 UTC, sloth-ontabasco approved these changes

2024-07-11 06:33 UTC, merged